### ISSUE TITLE
Need for $GROUP_TYPES_LIST_2_GROUP_TYPE

### ISSUE THREAD

**Issue by virgo30892** [nsoranzo/targetscan#2]
Hi,
I was going through the code and found that in targetscan_70.pl the hashmap GROUP_TYPES_LIST_2_GROUP_TYPE is never assigned any value the only time it is used that is after declaration is on line 886, which the statement will always be false. Then why is it even kept? 

		if ($GROUP_TYPES_LIST_2_GROUP_TYPE{$groupNumToSiteTypesList{$groupNumThisSite}})
		{
			$groupType = $GROUP_TYPES_LIST_2_GROUP_TYPE{$groupNumToSiteTypesList{$groupNumThisSite}};
		}
		else	# Unexpected set of groups
		{
			$groupType = $groupNumToSiteTypesList{$groupNumThisSite};
		}

**Comment by nsoranzo** [comment]
Good catch @virgo30892, I fixed it, thanks!
