### ISSUE TITLE
$numOverlapNt unitialized 

### ISSUE THREAD

**Issue by virgo30892** [nsoranzo/targetscan#3]
Hi,
 Is there a reason $numOverlapNt is unitialised in elsif block at line 701 of targetscan_70.pl

				elsif ( ($site1Start > $site2Start && $site1End < $site2End) ||
					($site2Start > $site1Start && $site2End < $site1End) )
				{
					groupThisPair($site1, $site2);
					$pairToDistance{"$site1 $site2"} = $numOverlapNt;

**Comment by nsoranzo** [comment]
It seems that `%pairToDistance` is unused, so I've removed it, which fixes the problem. Thanks again for the report @virgo30892!
